<br /><br />
<div id="view-content">
	<p>View script for controller <b>Index</b> and script/action name <b>activationlogin</b></p>
        
</div>

<?php

  if ($this->loginMessages) {
    foreach ($this->loginMessages as $message):
        echo $message.'<br>';
    endforeach;
}
?>
    <p><a href="<?php
    echo $this->url(
            array(
        'controller' => 'index',
        'action' => 'index'
            ), 'default', true)
    ?>">Główna strona</a></p>
