<br /><br />
<div id="view-content">
	<p>View script for controller <b>Index</b> and script/action name <b>changepassword</b></p>
</div>

<?php

  if ($this->loginMessages) {
    foreach ($this->loginMessages as $message):
        echo $message.'<br>';
    endforeach;
}
$this->form->setAction($this->url());
echo $this->form;

    if ($this->notifications) {
        foreach ($this->notifications as $notifications):
            echo $notifications . '<br>';
        endforeach;
    }
?>
    <p><a href="<?php
    echo $this->url(
            array(
        'controller' => 'index',
        'action' => 'index'
            ), 'default', true)
    ?>
          ">Główna strona</a></p>
